version: '3'
services:
  app:
    build: app
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
    environment:
      - FLASK_DEBUG=True
      - FLASK_APP=main.py
    expose:
      - 8000
    ports:
      - "8000:8000"

  client:
    build: frontend
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - app